import pandas as pd
d={'x':[1,2,3,4,5],'y':[2,4,5,4,5]}
df=pd.DataFrame(d)
print(df)
a=df['x'].mean()
b=df['y'].mean()
df['x-x1']=df['x']-a
df['y-y1']=df['y']-b
print(a,b)
df['(x-x1)2']=df['x-x1']**2
df['(y-y1)2']=df['y-y1']**2
df['(x-x1)(y-y1)']=df['x-x1']*df['y-y1']
z=df['(x-x1)(y-y1)'].sum()
h=df['(x-x1)2'].sum()
b1=z/h
b0=b-b1*a
df['y^']=[2.8,3.4,4,4.6,5.2]
df['y^-y1']=df['y^']-b
df['(y^-y1)2']=df['y^-y1']**2
e=df['(y^-y1)2'].sum()
g=df['(y-y1)2'].sum()
R=e/g
print(df)
print(z)
print(h)
print(b1)
print(b0)
print(e)
print(g)
print(R)